export enum JenisBatchIbuHamilEnum {
  IMUNISASITT1 = 'IMUNISASITT 1',
  IMUNISASITT2 = 'IMUNISASITT 2',
  IMUNISASITT3 = 'IMUNISASITT 3',
  IMUNISASITT4 = 'IMUNISASITT 4',
  IMUNISASITT5 = 'IMUNISASITT 5',
  TTD = 'TABLET TAMBAH DARAH',
  PMT = 'PEMBERIAN MAKANAN TAMBAHAN',
}
